[package]
name = "carbon_potential_estimator"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.5.4"
cubit = {git = "https://github.com/influenceth/cubit.git"}

[[target.starknet-contract]]
sierra = true
casm = true